### ISSUE TITLE
Cocoapods

### ISSUE THREAD

**Issue by coneybeare** [iGriever/TWSReleaseNotesView#1]
![y-u-no-guy](https://f.cloud.github.com/assets/35369/997091/c20137ae-09db-11e3-80ce-4469e6cf6f41.jpg)

y u no support!

**Comment by iGriever** [comment]
:) going to add Cocoapods support later this week ;)

**Comment by iGriever** [comment]
Just submitted a pull request to the Cocoapods Specs repo.

**Comment by iGriever** [comment]
Added support to CocoaPods:

pod 'TWSReleaseNotesView',       '~> 1.1.0'
