### ISSUE TITLE
Notification of view dismissal

### ISSUE THREAD

**Issue by jdandrea** [iGriever/TWSReleaseNotesView#15]
Is there any way to be notified that the view has been dismissed? I want to add it to a set of initialization steps, and I need to know when the view has gone away so that I know it's safe to proceed.

**Comment by iGriever** [comment]
Not at the moment. Feel free to open a pull request for that!

**Comment by jdandrea** [comment]
Unfortunately, I'm not in a position to do so (I wish!). Ah well.
