### ISSUE TITLE
Review Button Option

### ISSUE THREAD

**Issue by umekun123** [iGriever/TWSReleaseNotesView#18]
Wouldn't it be great if you can set "Review" button at the bottom?

Release note is the best time to ask for review without spamming users nowadays.
http://blog.supertop.co/post/77962740329/the-effective-way-to-ask-for-an-app-review

**Comment by iGriever** [comment]
Thanks for the suggestion, but I think this could be considered a little bit invasive!

**Comment by umekun123** [comment]
thanks for your reply, I understand!
