### ISSUE TITLE
Shows on first launch?

### ISSUE THREAD

**Issue by coneybeare** [iGriever/TWSReleaseNotesView#2]
I haven't tried it in my app yet ( see issue #1 ), but it looks like this will show the release notes [upon first run](https://github.com/iGriever/TWSReleaseNotesView/blob/2b515d7c2393d45f3e936aeed550824827f057cb/TWSReleaseNotesView/TWSReleaseNotesView.m#L203). Wouldn't it be wiser to check if the key exists at all, and if it doesn't, don't consider it a new version?

**Comment by iGriever** [comment]
Good point, I guess I should include a mode for that. At the moment, if the key doesn't exist the release notes are shown, and this is fine if you are not shipping the 1.0 version of your app.

**Comment by coneybeare** [comment]
....or if it is a user's first install. It should never be shown upon first ever launch of the app.

**Comment by iGriever** [comment]
In that particular case, I would leave to the developer this decision. So, I will add some options to decide what to do in case the key is not found.

**Comment by iGriever** [comment]
Just updated by adding a `+ (BOOL)isAppOnFirstLaunch` method and updating the `+ (BOOL)isAppVersionUpdated` to return `NO` if no previous version string if found.
