### ISSUE TITLE
iPad support

### ISSUE THREAD

**Issue by massimobio** [iGriever/TWSReleaseNotesView#3]
Nice component!
On iPad if you start the application in landscape the info panel is displayed in portrait.
Is rotation support (also iPhone) in the plans?
If not rotation, at least displaying the view in the current orientation?

**Comment by iGriever** [comment]
Rotation is already supported, even if I would like to transition to Auto Layout for a better orientation handling. I've just tried on a iPad test project and everything seems fine.

**Comment by massimobio** [comment]
Ah, my bad. I was showing the release notes from the main window in application:didFinishLaunchingWithOptions:
Thank you.
