### ISSUE TITLE
Localized remote release notes?

### ISSUE THREAD

**Issue by ddaddy** [iGriever/TWSReleaseNotesView#5]
Hi,
Thanks for this, it looks great.
I'm just wondering, will this take into account the localizations for different languages from the App Store?
Or would it be better to use local release notes with NSLocalizedString?

Thanks

**Comment by iGriever** [comment]
Thanks for the appreciation, very glad to hear that.

Speaking of the localization:
- for both the title and the close button title you have to use localizable strings;
- for the release notes text, if you choose the "local" version of course you have to use localizable strings as well, if you choose the "remote" version, the release notes are retrieved from the appropriate store, using the local country code for the current locale, obtained in the following way:

``` objective-c
NSLocale *locale = [NSLocale currentLocale];
NSString *countryCode = [locale objectForKey:NSLocaleCountryCode];
```

**Comment by ddaddy** [comment]
:+1: thanks
