### ISSUE TITLE
Automatically downsize the title content's font to avoid string cutting

### ISSUE THREAD

**Issue by ghost** [iGriever/TWSReleaseNotesView#8]
On multi language app, the _title_ field may have different lengths depending language.

When the title string length is bigger than the view length the text is cut. To handle this case add the feature to automatically downsize the font so the title fits with no cut.
The following method is helpful:

```
- (CGSize)sizeWithFont:minFontSize:actualFontSize:forWidth:lineBreakMode:
```

**Comment by iGriever** [comment]
It would be enough to set the `minimumScaleFactor` for the internal title label, which actually I didn't. Will fix on next release, thanks. Anyway, consider that for a good appearance the title is intended to be short, considering it involves only one row.

**Comment by ghost** [comment]
I agree with you with the fact the title must be short. I encountered this problem with development version of an app as the version number is quite long : v1.2.3-alpha build xxx for example.
Furthermore this could be helpful for larger screen display: developer fix a font size for the larger screen that is downsize for shorter screen.

I've notice that the view length does not adapt on larger screen: on iPad I expected the view to be larger. I open an issue for that point.

**Comment by ghost** [comment]
Maybe the version information should be separate from the title. For example center right above the title.
What do you think of this idea ?

**Comment by iGriever** [comment]
I set the number of lines for the title label to `2`. You can now set as a title string a text which contain a new line character, in order to break the title whatever you want:

``` objective-c
    TWSReleaseNotesView *releaseNotesView = [TWSReleaseNotesView viewWithReleaseNotesTitle:[NSString stringWithFormat:@"What's new in version\n%@:", currentAppVersion] text:@"• Create custom stations of your favorite podcasts that update automatically with new episodes\n• Choose whether your stations begin playing with the newest or oldest unplayed episode" closeButtonTitle:@"Close"];
```
